version: '3'

services:
  roach-ui:
    image: cockroachdb/cockroach
    command: start --insecure
    expose:
     - "8080"
     - "26257"
    ports:
     - "26257:26257"
     - "8080:8080"
    networks:
     - roachnet
  db-1:
    image: cockroachdb/cockroach
    command: start --insecure --join=roach-ui
    networks:
     - roachnet
    volumes:
     - ./data/db-1:/cockroach/cockroach-data
  db-init:
   image: cockroachdb/cockroach
   networks:
    - roachnet
   volumes:
     - ./setupdb.sh:/setupdb.sh
   entrypoint: "/bin/bash"
   command: /setupdb.sh
networks:
  roachnet:
